[package]
name = "example"
version = "0.1.0"
edition = "2024"

[features]
tracing = ["stack-debug/tracing"]

[dependencies]
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
stack-debug = { path = "../../" }